### ISSUE TITLE
 Unable to send message! to Splunk

### ISSUE THREAD

**Issue by bradpoulton** [x4n4th/LogToSplunk#1]
Hello, 

I am trying to get this plugin to work and I am not able to. I have tried on multiple spigot servers but i keep getting this error:

`[23:05:55 ERROR]: Unable to send message!
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_151]
        at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_151]
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139) ~[LogToSplunk-2.2.0.jar:?]
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155) ~[LogToSplunk-2.2.0.jar:?]
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284) ~[LogToSplunk-2.2.0.jar:?]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140) ~[LogToSplunk-2.2.0.jar:?]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[LogToSplunk-2.2.0.jar:?]
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261) ~[LogToSplunk-2.2.0.jar:?]
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165) ~[LogToSplunk-2.2.0.jar:?]
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167) ~[LogToSplunk-2.2.0.jar:?]
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272) ~[LogToSplunk-2.2.0.jar:?]
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124) ~[LogToSplunk-2.2.0.jar:?]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271) ~[LogToSplunk-2.2.0.jar:?]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[LogToSplunk-2.2.0.jar:?]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[LogToSplunk-2.2.0.jar:?]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[LogToSplunk-2.2.0.jar:?]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[LogToSplunk-2.2.0.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[LogToSplunk-2.2.0.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[LogToSplunk-2.2.0.jar:?]
        at com.splunk.sharedmc.logger.SingleSplunkConnection.sendData(SingleSplunkConnection.java:122) [LogToSplunk-2.2.0.jar:?]
        at com.splunk.sharedmc.logger.SingleSplunkConnection.run(SingleSplunkConnection.java:80) [LogToSplunk-2.2.0.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
`

I have also seen this error:

`[19:05:28] [Thread-18/ERROR]: Unable to send message!
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[?:1.8.0_131]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_131]
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139) ~[LogToSplunk-2.1.0.jar:?]
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155) ~[LogToSplunk-2.1.0.jar:?]
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284) ~[LogToSplunk-2.1.0.jar:?]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140) ~[LogToSplunk-2.1.0.jar:?]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[LogToSplunk-2.1.0.jar:?]
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261) ~[LogToSplunk-2.1.0.jar:?]
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165) ~[LogToSplunk-2.1.0.jar:?]
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167) ~[LogToSplunk-2.1.0.jar:?]
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272) ~[LogToSplunk-2.1.0.jar:?]
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124) ~[LogToSplunk-2.1.0.jar:?]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271) ~[LogToSplunk-2.1.0.jar:?]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[LogToSplunk-2.1.0.jar:?]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[LogToSplunk-2.1.0.jar:?]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[LogToSplunk-2.1.0.jar:?]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[LogToSplunk-2.1.0.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[LogToSplunk-2.1.0.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[LogToSplunk-2.1.0.jar:?]
        at com.splunk.sharedmc.SingleSplunkConnection.sendData(SingleSplunkConnection.java:122) [LogToSplunk-2.1.0.jar:?]
        at com.splunk.sharedmc.SingleSplunkConnection.run(SingleSplunkConnection.java:80) [LogToSplunk-2.1.0.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

I am able to send a test event to my HTTP event collector via a curl command from the Minecraft server, but when I enable the LogToSplunk plugin I do not see any events in Splunk. I am able to see events in the Minecraft console in the command line after i start Minecraft and the plugin gets enabled successfully. Here are the configurations I have tried and the versions of software I am using. 

Minecraft version: 1.12.1
Java Version: 1.8.0_151
LogToSplunk: 2.2.0
Operating system: Windows 10

I also tried on an Ubuntu server and a Centos 6 Server with Oracle Java and OpenJDK java. I have tried older versions of the plugin, but i can't seem to get it to work. My version of Splunk is 6.5.1. Any help is appreciated.

**Comment by bradpoulton** [comment]
I finally figured out the issue. My Splunk HTTP Event collector was set to use SSL. This plugin doesn't support SSL. By turning off SSL on my Splunk HTTP EC, the logs were sent fine from Minecraft.
